### ISSUE TITLE
Crab can't drop heavy items

### ISSUE THREAD

**Issue by FoodAbuse** [FoodAbuse/stabo-crabo-game#20]
**Description**

If player ALT+Tab's out of game whilst holding/dragging an item, they cannot release it

**Version**

V0.2-Alpha (Semester 2, September Pre PGF Build)

**To Reproduce**

1. Launch Build
2. Grab any draggable item
3. Hold ALT+Tab and then return to the game

**Expected behavior**
The player should ideally drop the item upon alt-tabbing, although this understandably might be difficult to get working. At the minimum we will need the player to be able to drop the item when they return to the game

**Screenshots**
<img width="227" alt="image" src="https://github.com/FoodAbuse/stabo-crabo-game/assets/106326154/26d5ebea-b7a1-4bc8-a4d8-f42ab256d8ba">

**Desktop System (please complete the following information):**
- OS: Windows 11

**Comment by ZachariaWinter** [comment]
Ok so the issue here is that for heavy obects a character joint between it and the player.
On MB1 up it should destroy that joint and 'drop' the object.
However even when holding the mouse through alt tabbing, away and then back, and then releasing with the game active, it is not destroyed.
Re-pressing the mouse button adds a second joint, and releasing destroys that new joint.

I can change the code to destroy all character joints.
Which shouldn't be a bad thing, as so far the only thing that creates these joints is the grab mechanic.
But it will important to keep in mind if we ever have joints disspearing in future.

**Comment by ZachariaWinter** [comment]
Did as I said I would, and it works.
To be clear, when you alt + tab, the object stays connected to you when you release LMB.
However now when you re-click and release, it becomes unattached.

It is possible that I can look for code that detects what the active window is, and destroy joints based ont that.
However that will take longer to reaserach and implement, and this issue should not come up during our playtests and showcases, as there is no reason to be in any other window while the game is running. (might switch to a different window for a survey or something).
