### ISSUE TITLE
NPCs lying down slide around after being stabbed

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#26]
Description
Lying down NPCs play their getting stabbed animation, lie back down, and slide to a new location.

Version
n/a

To Reproduce
Tested in level 2:
Stabbed the NPC on the rightmost beach

Expected behavior
They shouldn't slide around probably

Desktop System (please complete the following information):

    OS: Windows10

**Comment by ZachariaWinter** [comment]
Yeah this one is solved by reducing the 'flee time' parameter on the NPC to 0.
Currently there is code in palce for sitting npcs to be stabbed, flee, return to spot, and sit back down again (although the sit animation plays twice for some reason).
But that code is not in place for sleeping people, because they play a different 'hurt' animation that doesn't snap them to a standing pose, and so I'm not sure it will look great for them to then be on their feet running away.

so for now setting flee time to 0 is the solution.
and I have done so for the NPC in question.
