### ISSUE TITLE
Donut cop won't pick up donut

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#31]
**Description**

The donut cop struggles to pick up the donut while the crab is around. Additionally, he struggles if the donut is somehow placed behind him. It is confusing more than game breaking as donuts respawn.

**Version**
pgf

**To Reproduce**

1. Grab donut as usual, bring to cop
2. The cop will not chase the donut even if you leave it
3. leave the area, the cop will chase the donut
4. If you want to be block, walk up to the cops and let go of the donut just before they kick you, preventing you from reaching the donut

**Expected behavior**
The cop should prioritise the donut over the crab or else there is no instant feedback.

**Desktop System (please complete the following information):**

    OS: Windows10

**Additional context**
n/a

**Comment by ZachariaWinter** [comment]
Leaving Open for now because we may desire to fix this a different way.
Changed FOV script to prioritise:
1: objects held by player
2: objects on the ground
3: the player (when defending or guarding)

beacuse of the changes to the way that the crab grabs light objects (the collider is turned off), the fov script will not actually detect any light object held by the player at the moment.
This is conceptually a problem, but technically not yet. Because so far the only object that we really need NPCs to see while the crab is holding them is the child that protects the bucket, and that is a heavy object.

The cop therefore does not see the donut while it is held, but they see it as soon as the palyer lets go, even if the crab is still in view which is an improvment over how this issue stood previously.

could consider changing the light grab to turn the collider to trigger instead of turning it off, but that may have other unforseen consequences

**Comment by ZachariaWinter** [comment]
Based on discussion with group, we want the cop to see the donut in the crab's grip. So will trial setting collider to trigger

**Comment by ZachariaWinter** [comment]
Made the change where collider is set to trigger and so far everything works as intended.
If it causes more issues, they can be opened and written up separately.
