### ISSUE TITLE
Bouncer at restaurant struggles to locate crab

### ISSUE THREAD

**Issue by mochi05** [FoodAbuse/stabo-crabo-game#33]
**Description**
The bouncer sometimes turns around too much, meaning he loses track of the crab and just sort of stands around facing backward.

**Version**
pgf build

**To reproduce**

1.  Simply run around the bouncer enough times and he will inevitably get confused
2.  It usually doesn't last too long but ruins immersion

**Additional notes**
My recommendation; somehow keep the bouncer always facing outward (ala guards from Majora's Mask)

**Comment by ZachariaWinter** [comment]
I had the NPC 'gaurding' behaviour previously written that way. NPCs would constantly face the crab while 'guarding' an area from the player.
This made it look weird when the cop went back and forth from grabbing the donut, and then the crab was seen and they would rush back to guard, but face the wrong way the whole time.

Now that the donut is the prioirty (due to recent change) this might not be an issue any more, so I will add the rotation back in and see what happens

**Comment by ZachariaWinter** [comment]
Brought the old bit of code back in and modified it so that the y position is ignored in the look at rotation function.
Tested in scene and it seems to work fine
